import test from 'node:test';
import assert from 'node:assert/strict';
import {createApprovedContent} from '../lib/approvedContent.js';
import {createHandler} from '../api/social/media-library.js';
const company='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const make=(i,owner=company)=>{const id=`33333333-3333-4333-8333-${String(i).padStart(12,'0')}`,base=owner+'/'+id+'/';return {id,company_id:owner,title:'Photo '+i,kind:i%2?'IMAGE':'REELS',original_ext:'jpg',master_path:base+'master.jpg',review_path:base+'review.'+(i%2?'jpg':'mp4'),poster_path:base+'poster.jpg',publishing_path:base+'social.'+(i%2?'jpg':'mp4'),status:i%3?'APPROVED':'IN_REVIEW',project_label:i%2?'Launch':'Summer',created_at:'2026-10-01',caption:''};};
function setup({leak=false,fail=false}={}){
 const calls=[],signed=[],rows=Array.from({length:60},(_,i)=>make(i+1)).concat(make(99,other));
 const db={storage:{from(){return {async createSignedUrl(path,ttl){signed.push(path);assert.equal(ttl,300);return {data:{signedUrl:'https://example.test/'+path}};}};}},from(table){assert.equal(table,'social_approved_assets');let filters=[],range=[0,24];const q={select(){return q;},eq(k,v){calls.push([k,v]);filters.push(r=>r[k]===v);return q;},ilike(k,v){calls.push([k,v]);filters.push(r=>r[k].toLowerCase().includes(v.slice(1,-1).toLowerCase()));return q;},order(){return q;},range(a,b){range=[a,b];return q;},then(resolve,reject){return Promise.resolve(fail?{error:{}}:{data:(leak?rows:rows.filter(r=>filters.every(f=>f(r)))).slice(range[0],range[1]+1)}).then(resolve,reject);}};return q;}};
 return {service:createApprovedContent({getDb:()=>db}),calls,signed};
}
test('history paginates beyond latest 30 and signs only tenant posters',async()=>{const {service,calls,signed}=setup();const first=await service.library({companyId:company});const second=await service.library({companyId:company},{page:'1'});assert.equal(first.assets.length,24);assert.equal(second.assets.length,24);assert.equal(first.hasMore,true);assert.notEqual(first.assets[0].id,second.assets[0].id);assert.ok(calls.every(([k,v])=>k!=='company_id'||v===company));assert.ok(signed.every(p=>p.startsWith(company+'/')&&p.endsWith('/poster.jpg')));assert.equal(first.assets[0].master_path,undefined);assert.equal(first.assets[0].previewUrl,undefined);});
test('filters combine within session tenant',async()=>{const {service}=setup();const r=await service.library({companyId:company},{filter:'photos',project:'Launch',q:'Photo 1'});assert.ok(r.assets.length);assert.ok(r.assets.every(a=>a.kind==='IMAGE'&&a.projectLabel==='Launch'&&a.title.includes('Photo 1')));const a=await service.library({companyId:company},{filter:'approved'});assert.ok(a.assets.every(a=>a.status==='APPROVED'));});
test('foreign session returns only its own assets',async()=>{const {service,signed}=setup();const r=await service.library({companyId:other});assert.equal(r.assets.length,1);assert.ok(signed.every(p=>p.startsWith(other+'/')));});
test('rejects tenant override, malformed filters and backend failures',async()=>{for(const options of [{companyId:other},{page:'-1'},{page:'1.5'},{filter:'all,APPROVED'},{q:['x']},{q:'x'.repeat(161)}])await assert.rejects(setup().service.library({companyId:company},options),{status:400});await assert.rejects(setup({fail:true}).service.library({companyId:company}));});
test('literal search escapes SQL pattern wildcards',async()=>{const {service,calls}=setup();await service.library({companyId:company},{q:'50%_'});assert.ok(calls.some(([k,v])=>k==='title'&&v==='%50\\%\\_%'));});
function res(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(data){this.data=data;return this;}};}
test('library endpoint requires auth, rejects writes and never trusts query tenant',async()=>{let count=0;const h=createHandler({verify:()=>{throw Error();},service:{library(){count++;}}});let r=res();await h({method:'GET',headers:{},query:{}},r);assert.equal(r.code,401);assert.equal(count,0);r=res();await h({method:'POST',headers:{}},r);assert.equal(r.code,405);const own=createHandler({verify:()=>({companyId:company}),service:setup().service});r=res();await own({method:'GET',headers:{authorization:'test'},query:{companyId:other}},r);assert.equal(r.code,400);assert.equal(r.headers['Cache-Control'],'no-store');});

test('Preview library demo is inaccessible in production',async()=>{const {default:handler}=await import('../api/qa/media-library.js');const old=process.env.VERCEL_ENV;process.env.VERCEL_ENV='production';try{const r={...res(),send(data){this.data=data;return this;}};handler({method:'GET',headers:{},url:'/api/qa/media-library'},r);assert.equal(r.code,404);}finally{if(old===undefined)delete process.env.VERCEL_ENV;else process.env.VERCEL_ENV=old;}});
