// Shared local staff UI and inert Vercel Preview demonstration. No credentials here.
export function adminUploadPage(nonce, demo=false) {
 return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>JMN · Upload Client Content</title><style>
*{box-sizing:border-box}body{margin:0;background:#121316;color:#eeeef3;font:14px/1.5 Inter,system-ui,sans-serif}main{max-width:640px;margin:32px auto;padding:24px;background:#191a1e;border-radius:10px}h1{font-size:22px;font-weight:600;margin:8px 0}p{color:#a6a8b2;font-size:13px}.eyebrow{font-size:11px;color:#c8b6f1}label{display:block;margin:20px 0 8px;font-size:13px}input,select,button{font:inherit;max-width:100%;border-radius:8px}input,select{width:100%;min-height:44px;background:#222329;border:1px solid #3b3d46;color:#eeeef3;padding:10px 12px}button{min-height:44px;border:0;background:#805ce6;color:white;padding:10px 16px;cursor:pointer}button:disabled{opacity:.5;cursor:default}:focus-visible{outline:2px solid #c0a7ff;outline-offset:3px}.drop{border:1px dashed #535460;border-radius:8px;padding:20px;text-align:center;background:#202126}.drop input{border:0;padding:8px;min-width:0;font-size:12px}.drop.drag{border-color:#b69bea}#file-info,#status{overflow-wrap:anywhere}footer{position:sticky;bottom:0;background:#191a1e;padding:16px 0 0;display:flex;justify-content:flex-end}#status{white-space:pre-wrap}small{color:#a6a8b2}fieldset{border:0;margin:0;padding:0;min-width:0}@media(max-width:680px){main{margin:8px;padding:16px}input,select{font-size:16px}footer button{width:100%}}@media(prefers-reduced-motion:no-preference){button{transition:background 160ms}}
</style><main><span class="eyebrow">${demo?'PREVIEW QA · FICTIONAL DATA':'JMN STAFF · PRIVATE WORKSTATION'}</span><h1>Upload Client Content</h1><p>Send finished work for review. The original stays full quality.</p><form id="upload"><fieldset id="fields"><label for="client">Client</label><select id="client" required><option value="">Choose a client</option></select><label for="project">Project / Campaign <small>· optional label</small></label><input id="project" maxlength="160" placeholder="September campaign"><label for="title">Title</label><input id="title" maxlength="160" required placeholder="A title your client will recognize"><label for="media">Media</label><div class="drop" id="drop"><span>Drop a photo or video here</span><input id="media" type="file" accept=".jpg,.jpeg,.png,.mp4,.mov" aria-label="Choose client media"><p id="file-info">JPEG, PNG, MP4 or MOV · up to 500 MiB, subject to storage limits.</p></div></fieldset><p id="status" role="status" aria-live="polite">${demo?'Visual demo only. No files are uploaded or saved.':'Connecting to your private upload session…'}</p><footer><button id="submit" type="submit" disabled>Send for review</button></footer></form></main><script nonce="${nonce}">
const demo=${JSON.stringify(demo)},token=location.hash.slice(1);history.replaceState(null,'',location.pathname);const $=id=>document.getElementById(id),status=$('status');let selected=null;
async function request(path,options={}){const response=await fetch(path,{...options,headers:{...options.headers,Authorization:'Bearer '+token}});const data=await response.json();if(!response.ok)throw Error(data.error||'Upload unavailable.');return data;}
function choose(file){selected=file||null;$('file-info').textContent=file?file.name+' · '+(file.size/1048576).toFixed(1)+' MiB · '+(/\\.(jpg|jpeg|png)$/i.test(file.name)?'Photo':'Reel'): 'Choose a file';}
$('media').onchange=()=>choose($('media').files[0]);$('drop').ondragover=e=>{e.preventDefault();$('drop').classList.add('drag')};$('drop').ondragleave=()=>$('drop').classList.remove('drag');$('drop').ondrop=e=>{e.preventDefault();$('drop').classList.remove('drag');if(!$('fields').disabled)choose(e.dataTransfer.files[0]);};
(async()=>{try{const data=demo?{companies:[{id:'demo',business_name:'Demo Studio'}]}:await request('/companies');for(const c of data.companies){const o=document.createElement('option');o.value=c.id;o.textContent=c.business_name;$('client').append(o)}$('submit').disabled=false;if(!demo)status.textContent='A protected review copy is generated automatically. Keep this window open until delivery finishes.';}catch(e){status.textContent=e.message}})();
$('upload').onsubmit=async e=>{e.preventDefault();if(demo){status.textContent='Visual QA only — upload and delivery are disabled.';return;}if(!selected||!selected.size||selected.size>524288000||!(/\\.(jpg|jpeg|png|mp4|mov)$/i.test(selected.name))){status.textContent='Choose a supported file up to 500 MiB.';return;}$('fields').disabled=true;$('submit').disabled=true;status.textContent='Preparing protected previews and sending for review… This may take several minutes.';try{const data=await request('/upload',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-JMN-Metadata':encodeURIComponent(JSON.stringify({companyId:$('client').value,title:$('title').value,projectLabel:$('project').value,filename:selected.name}))},body:selected});status.textContent='Sent for review. Your client can find it in Social Command Center.\\nReference: '+data.assetId;selected=null;$('upload').reset();$('file-info').textContent='Choose another file when ready.';}catch(e){status.textContent=e.message;}finally{$('fields').disabled=false;$('submit').disabled=false;}};
</script></html>`;
}
