import {reviewPoster} from './publishingQaMedia.js';
export function mediaLibraryPreviewPage(nonce){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Media Library · Preview QA</title><link rel="stylesheet" href="/social-command-center.css"><link rel="stylesheet" href="/social-publishing.css"><link rel="stylesheet" href="/media-library.css"><style>body{margin:0;background:#111214;color:#f2f2f5;font-family:system-ui}*{box-sizing:border-box}.shell{max-width:1200px;margin:auto;padding:24px}.qa-tools{padding:16px;border-bottom:1px solid #444;display:flex;gap:16px;flex-wrap:wrap}.qa-tools select{padding:8px}.btn{cursor:pointer}.btn:disabled{opacity:.4}#demo{container-type:inline-size}@container(max-width:560px){.media-library .approved-assets,.library-controls{grid-template-columns:1fr}.media-library .content-actions{flex-wrap:wrap}}</style></head><body data-media-library="true"><aside class="qa-tools"><strong>Preview QA · fictional media only</strong><label>Scenario <select id="scenario"><option>Populated</option><option>Empty</option><option>Error</option><option>Loading</option><option>No Instagram</option></select></label><label>Viewport <select id="width"><option value="100%">Desktop</option><option value="390px">Mobile 390px</option></select></label><span>No uploads, saves or publishing.</span></aside><main id="demo" class="shell"><h1>Media &amp; Deliverables</h1><p>Your permanent collection of photos, reels and campaigns.</p><div id="library"></div><div id="composer"></div></main><script nonce="${nonce}" src="/social-publishing.js"></script><script nonce="${nonce}">
const poster=${JSON.stringify(reviewPoster)};
const rows=Array.from({length:55},(_,i)=>({id:'demo-'+i,title:i===0?'A very long campaign title to verify wrapping on a small screen':'Studio story '+(i+1),kind:i%2?'IMAGE':'REELS',status:i%3?'APPROVED':'IN_REVIEW',projectLabel:i%2?'Launch':'Summer',createdAt:'2026-09-20T12:00:00Z',caption:'A fictional studio story.',posterUrl:poster,previewUrl:poster}));
let view,composer;
function mount(){view?.close();composer?.close();document.getElementById('library').replaceChildren();document.getElementById('composer').replaceChildren();const scenario=document.getElementById('scenario').value;
const request=async p=>{if(['review','preview'].includes(p.command))return {...rows.find(a=>a.id===p.assetId),kind:'IMAGE'};throw Error('Preview QA only. Approval, downloads, saves and publishing are disabled.');};
composer=window.JmnPublishing.mount(document.getElementById('composer'),{composerOnly:true,account:{username:'demo_studio',scopes:[]},approvedRequest:request,request:async()=>{throw Error('Preview QA only. Saving and publishing are disabled.');},connect:()=>{}});
view=window.JmnPublishing.mountContent(document.getElementById('library'),{library:true,request,onPost:scenario==='No Instagram'?null:a=>composer.compose(a),listRequest:async f=>{if(scenario==='Loading')return new Promise(()=>{});if(scenario==='Error')throw Error('Unable to load your media library. Please retry.');const found=(scenario==='Empty'?[]:rows).filter(a=>(!f.q||a.title.toLowerCase().includes(f.q.toLowerCase()))&&(!f.project||a.projectLabel===f.project)&&(f.filter==='all'||f.filter==='photos'&&a.kind==='IMAGE'||f.filter==='reels'&&a.kind==='REELS'||f.filter==='approved'&&a.status==='APPROVED'));const start=Number(f.page)*24;return {assets:found.slice(start,start+24),hasMore:found.length>start+24};}});}
document.getElementById('scenario').onchange=mount;document.getElementById('width').onchange=e=>{document.getElementById('demo').style.width=e.target.value;};mount();
</script></body></html>`;}
