name: Manual database backup
on:
  workflow_dispatch: {}

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install postgresql-client 17
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-common
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt-get install -y postgresql-client-17
      - name: Dump roles
        run: /usr/lib/postgresql/17/bin/pg_dumpall --dbname="${{ secrets.SUPABASE_DB_URL }}" --roles-only -f roles.sql
      - name: Dump schema
        run: /usr/lib/postgresql/17/bin/pg_dump "${{ secrets.SUPABASE_DB_URL }}" --schema-only -f schema.sql
      - name: Dump data
        run: /usr/lib/postgresql/17/bin/pg_dump "${{ secrets.SUPABASE_DB_URL }}" --data-only -f data.sql
      - name: Upload backup files
        uses: actions/upload-artifact@v4
        with:
          name: jmn-backup-${{ github.run_id }}
          path: |
            roles.sql
            schema.sql
            data.sql
          retention-days: 14
